data:
  images_path: "../logo-detection-1/train"
  annotations_file: "../logo-detection-1/train/_annotations.coco.json"
  num_train_images: 50 # Keep high enough to ensure that at least one of each label is seen in training. 2500 is a good minimum
  num_test_images: 10

training:
  n_epochs: 20
  learning_rate: 3e-6  # Keep very low
  save_eval_images: true
  use_class_weight: true 
  weight_decay: 0.1  # default
  confidence_threshold: 0.01  # This can be quite low and still achieve good results
  iou_threshold: 0.6  # For nms
  # NOTE: Use these values for benchmarking to stay consistent with YOLO, fasterRCNN, SSD, DETR,... etc
  #   confidence_threshold: 0.01  
  #   iou_threshold: 0.45

  
  
